### ISSUE TITLE
running yanagi on .fastq.gz files

### ISSUE THREAD

**Issue by JamalEH** [mgunady/yanagi#2] opened 2020-03-03 23:10 UTC
Dear Team,

While tying to run yanagi on .fastq.gz read files, I got the following error:
index:
unmated read(s): /home/jelhasnaoui/ref/OriginalData/DeBortoli/03_2016_RNASeq_Noncoding/Sample_LNA_CTRL_1_R1.fastq.gz
output:
num. threads: 1
max num. hits: 200
quasi-coverage: 0
no output: false
sensitive: true
strict check: true
fuzzy intersection: false
do chaining : false
selective alignment: false
no orphans: false
no dovetail: false
====================
terminate called after throwing an instance of 'cereal::RapidJSONException'
  what():  rapidjson internal assertion failure: IsObject()
[2020-03-04 00:01:40.050] [stderrLog] [warning]

NOTE: It appears you are running rapmap without the selective-alignment (`--selAln`) option.
Selective alignment can generally improve both the sensitivity and specificity of mapping,
with only a moderate increase in use of computational resources.
Unless there is a specific reason to do this (e.g. testing on clean simulated data),
`--selAln` is generally recommended.

[2020-03-04 00:01:40.050] [stderrLog] [info]
command line options
====================
index:
unmated read(s): /home/jelhasnaoui/ref/OriginalData/DeBortoli/03_2016_RNASeq_Noncoding/Sample_LNA_CTRL_1_R2.fastq.gz
output:
num. threads: 1
max num. hits: 200
quasi-coverage: 0
no output: false
sensitive: true
strict check: true
fuzzy intersection: false
do chaining : false
selective alignment: false
no orphans: false
no dovetail: false
====================
terminate called after throwing an instance of 'cereal::RapidJSONException'
  what():  rapidjson internal assertion failure: IsObject()
Done
Elapsed Time:  0.4534430503845215
Done
Elapsed Time:  0.4746520519256592
Processing Alignments...
Mapped Reads: 0 Unmapped Reads: 0 Unmapped Due Txs: 0 Unmapped Due Direction: 0
Done!
Elapsed Time:  0.00027108192443847656
Writing Segments Counts...
Error
Traceback (most recent call last):
  File "yanagi.py", line 62, in main
    alignSegments.main()
  File "/vol1/Analysis/DeBortoli/RNASeq_Noncoding_LNA_siRNA/yanagi-0.1/segmentsAligner.py", line 29, in main
    alignAndCount(args.segs_ref_file, args.output_file, args.align_command1, args.align_command2)
  File "/vol1/Analysis/DeBortoli/RNASeq_Noncoding_LNA_siRNA/yanagi-0.1/lib/SegCounter.py", line 265, in alignAndCount
    writeSegPairCounts(outf, segPairs_counts, newsegPairs_counts, segPairs_txs, segsDict)
  File "/vol1/Analysis/DeBortoli/RNASeq_Noncoding_LNA_siRNA/yanagi-0.1/lib/SegCounter.py", line 29, in writeSegPairCounts
    for segPair in sorted(segPairs_counts.iterkeys()):
AttributeError: 'Counter' object has no attribute 'iterkeys'

Should I change the read file from .fastq.gz file to ".fa" format?
Can I also run RapMap using "--selAln" option?

Thank you!
Kind regards,
Jamal.

**Comment by mgunady** [comment] 2020-03-04 11:03
Jamal,

Working with .gz files is fine, that's not the cause of the problem.
Can you share the command you used to run RapMap? Make sure you follow the instructions mentioned in our tutorial page, including our branch for yanagi-count, which already uses selective alignment (check: https://github.com/mgunady/Yanagi-count)

**Comment by JamalEH** [comment] 2020-03-04 11:13
Dear mgunady,
Thank you for your prompt reply!

To index and align I used the following commands:
## index:
 nohup ../../RapMap-latest_linux_x86_64/bin/rapmap quasiindex -t ./segs_75.fa -i RapMap_index &
##align:
nohup python yanagi.py align -ref results/annotation/segs_75.fa.meta -o Sample_LNA_CTRL1_seg_counts.txt -cmd1 'RapMap-latest_linux_x86_64/bin/rapmap quasimap -i results/annotation/RapMap_index -r /home/jelhasnaoui/ref/OriginalData/DeBortoli/03_2016_RNASeq_Noncoding/Sample_LNA_CTRL_1_R1.fastq.gz' -cmd2 'RapMap-latest_linux_x86_64/bin/rapmap quasimap -i results/annotation/RapMap_index -r /home/jelhasnaoui/ref/OriginalData/DeBortoli/03_2016_RNASeq_Noncoding/Sample_LNA_CTRL_1_R2.fastq.gz' &

Kind regards,
Jamal.

**Comment by JamalEH** [comment] 2020-03-04 11:25
Apparently, I have to use the following command for indexing, instead of the previous one?:
> rapmap quasiindex -i segs_index -t segs.fa --segments segs.fa.meta --keepDuplicates

Kind regards,
Jamal.

**Comment by mgunady** [comment] 2020-03-04 18:10
The commands you used before aren't the most up-to-date recommended way to run our pipeline.
Since Nov 2019, major updates into our pipeline and the use of rapmap (including providing internal segments-support into Rapmap), so make sure first your yanagi code version is updated (or at least cloned the repo after Nov 2019). Then yes follow the rest of the tutorial and use the following index command:
> rapmap quasiindex -i segs_index -t segs.fa --segments segs.fa.meta --keepDuplicates

**Comment by JamalEH** [comment] 2020-03-04 21:00
Dear Mohamed,
Thank you for your reply!
Ok, I was using the oldest version of your tool since it was the one mentioned within your paper.
I will now follow the instructions of this page https://github.com/mgunady/Yanagi-count from installation to data processing.

I will keep you updated on the performance of the tool on my RNA-Seq dataset, as compared to Whippet, PSI-sigma, in term of alternative splicing changes.

Kind regards,
Jamal.

**Comment by mgunady** [comment] 2020-03-05 02:00
I will close this issue then and you can always start new issues
Thanks,

**Closed as completed by mgunady** 2020-03-05 02:00 UTC
